entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'
api:
  dashboard: true
certificatesResolvers:
  lets-encrypt:
    acme:
      email: yungen.lu@outlook.com
      storage: ce/acme.json
      dnsChallenge:
        provider: namedotcom
        delayBeforeCheck: 0
providers:
  docker:
    watch: true
    network: web
  file:
    filename: traefik_dynamic.yaml
