http:
  middlewares:
    simpleAuth:
      basicAuth:
        users:
          - 'admin:$apr1$/aLtrVMz$Pmuhm6B3z/3VliBV2ycLy0'
  routers:
    api:
      rule: Host(`monitor-code.yungen.studio`)
      entrypoints:
        - websecure
      middlewares:
        - simpleAuth
      service: api@internal
      tls:
        certResolver: lets-encrypt