addons:
  sonarcloud:
    organization: "yungen-lu"
    token: 
      secure: "JWv4CgeFYX1fWf/V6KzYLBADpxXsFAjpPnwYeIxuuKX0rwCChqgwP9NfupzsS1QRdEJFuKlgbwH/5VAKNuq11LWfL6s8i0po3Cf34Is90cT3fp5iQqDd2nzFvl/fZcsBtpuj6xTm+mJSJ4Ja1IANA+/9NoqwXytsL1rIWLxMkiYh65XAPh9Sspgex6h/M9MkWK88NUYVMTpgFAhsQqwBnpx7rHH268+JP+TXDaoNNXsG191/eDTUjR7KYxiXqonOcOQaumEhGA6HkCd0MblOlOuyhg44PiM5lWRfYKgNW7CN+cVhyv5ADCPjMXkGNLFsAUuzI8emnQV5h4SOWXO0pPRDBK5QNaOYhmxESdoz1F9caubNRvswiBcecmie3emE5i36fLRv5gy/aItYV+h0JGaEJHvP51smnt1fbdu7hYW1EKBSDQDfPqB3Eq8NUOAX3L8fptreS22O8AQ1lUHIqEgIam5hldaBe2yZVnsYoU4W1ifYuLNvXswbntA108TvwZyjWGrGDWbuVcRow1SgY0gUOX9jflZp8QAAHR1MWVTbjUo+P4iCTFNhHXe3CeX46KB+Pom2r8fQ+FQMi3Jir5Cjjh0agxiJ8HgRCB8ptMfcGqjOWLukvzBm9QEbOTvS0+GdgG4Qs6jebAu/RzH+ZX+cqMdEMupXMG8Z25+pWNI="

script:
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarScanner) into the "bw-output" folder
  - build-wrapper-linux-x86-64 --out-dir src/app/build_wrapper_output_directory make clean all # And finally run the SonarCloud analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=src/app/build_wrapper_output_directory