addons:
  sonarcloud:
    organization: "yungen-lu"
    token: 
      secure: "apTP3cvVWZwaOr6Zx8E69aPmVypGMdpPY1GvQxBtunPzpJ2gQc6+dx2vqdEjA8HVbTNBBStPdRnXC3lncoV5DWzsfs/q81G8YzDQDgV7HXsO77Y6s8wEzajJ+LbxeOtu2cPmONBWxnsYLQPqqONFDFthac/qU48bfjEVu4lbI2iN/gUpveyhLq+8D/Pp4Xwvnzdgk8fQkP7c7kW2J8XEoh5k7h/HWeGhHX5KSIoL0w+szEYS0B/TpPXR8xk1ZRc7kcZFf1auKmDXIm+mFXGR1qSDtdtJd2hInptUMIWXj/5yLOBkmQBmDjxEwhMTKPz51Ck70pajehuOlq2+pgHCpExbl6XGCVMHaig4T9+6zCScBzOz664ulG1nA2R0Yc7ajSkkMec1hwnxqvgas5zA1ogzIFzwTQWGKKnMBwEZ1QEoYEjPEDe4d4wjyQbywhHe+Ke/J2v74msUY7aalibTzKJ9+AqSfyfeXXpgpnzqxoSoYSrrRMWCv10WHUJ9QZnLbLKn72JU7SAGO2UUQ8WcKE/iQH+4X53JSVVzu7Dspbzu9IkrIOgsZ7KbYruaVWdpTNBEYYFhyBk2sZRew8qTM+Kfcm2e8s2J3W/2n+q4bHu3bITVKqKk8+WMtPZPqjuTlTpJSjgL7JzKRunRYUu243tDxD76Pb3Wv4xlrjBl4v0="

script:
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarScanner) into the "bw-output" folder
  - build-wrapper-linux-x86-64 --out-dir code.yungen.studio/app/build_wrapper_output_directory make clean all # And finally run the SonarCloud analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=code.yungen.studio/app/build_wrapper_output_directory