addons:
  sonarcloud:
    organization: "yungen-lu"
    token: "TvSux/luMvxIylvT/+CPo3N0i77F7Sny/RDr1VjyxpkdjYsO5bS9bwrSHCkBrjun7+w314FwNa1oEnlzx6eU0JzD/TeMZZNTSI0CRmvFJMeUj80Y7tmexdkDJJKxjaTWAZsNrAoYA0PvlGjCXCB+OM+R7Ja4fg/Uy5R3SSAO0Wd96ppQGgns3p3XfTLH877JpCFdO166oi8IbupRSa3qUcGLEAfCHW0of4oVnN69uSToAmCSR2hkbJzIovnTpgu5F3ot46GkZRWbIW/NianWGV1lGfNh6CltVWjzf5cPw/Y2Zt8OFWsXpz7IcQEcg9v7oRaqVD69l78RZszwDLgtcwVoGqv05v3mhKcoIqPGjWj0yVLU8/4v/LSzxZXVHexygS3eh2AGVrKQqm+5EMY8Qb3Jg5WrX2+2XoEjMs8UDfOkmTBgPm3/wyYdiPS8IfECajjW83hxXEChzFjs53HBho1CNAzebRiAhEvdpCDy+ieFtGebbFjj9BBP2Bgx0H0ELKZiAZLzC/xSO9o/D3REO19w/NUowNFo9pYk/pBlBd4BQktPIHr2W+IrKd/9BwklegKOMq9fkn8L/u9DbVOoAALpq9QTBiO7b4j8k8/Hh+KIPt9ygnwdPGlXPc1JJ9Y2nF8HkoPgnVdYJOSvkN1E06eZwx5hFZZX9ciFIolX3RE="

script:
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarScanner) into the "bw-output" folder
  - build-wrapper-linux-x86-64 --out-dir code.yungen.studio/app/build_wrapper_output_directory make clean all # And finally run the SonarCloud analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=code.yungen.studio/app/build_wrapper_output_directory